import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className="scroll-smooth ">
      <body
        className="font-Dana text-gray-900 dark:text-white
       bg-gray-100 dark:bg-gray-900"
      >
        {children}
      </body>
    </html>
  );
}
